/**
 * ReadOnlyView Organism - Submitted Order Summary
 *
 * Displays order confirmation after successful submission.
 * Shows:
 * - Order ID (generated by server)
 * - Order details (symbol, notional, direction, type)
 * - Current status ("Pending Fill")
 * - Action buttons (Amend, New Order)
 *
 * Why a separate view?
 * - Prevents accidental edits after submission
 * - Provides clear confirmation to user
 * - Enables "Amend" workflow (double-click to edit)
 *
 * Amend Flow:
 * 1. User clicks "Amend" → editMode = "amending"
 * 2. Form becomes editable (only editableFields from orderConfig)
 * 3. User makes changes → submits again
 *
 * New Order Flow:
 * 1. User clicks "New Order" → resets form, editMode = "creating"
 * 2. Form clears, ready for fresh order entry
 *
 * Used by: OrderForm (shown when editMode === "viewing").
 */

import { useShallow } from "zustand/react/shallow";

import { useOrderEntryStore } from "../../store";
import { formatCurrency } from "../../utils/numberFormats";

import styles from "./ReadOnlyView.module.scss";

export const ReadOnlyView = () => {
  // Store selectors
  const values = useOrderEntryStore(useShallow((s) => s.getDerivedValues())); // Full order state
  const amend = useOrderEntryStore((s) => s.amendOrder); // Enter amend mode
  const reset = useOrderEntryStore((s) => s.resetFormInteractions); // Clear form
  const setStatus = useOrderEntryStore((s) => s.setStatus); // Update app status

  /**
   * Handle "New Order" button click.
   * Resets form and returns to creating mode.
   */
  const handleNewOrder = () => {
    reset(); // Clear dirtyValues, errors, touchedFields
    setStatus("READY"); // Ensure status is ready (not error)
  };

  return (
    <div className={styles.container}>
      {/* Success Header */}
      <div className={styles.header}>
        {/* Checkmark icon */}
        <div className={styles.iconWrapper}>
          <svg className={styles.icon} fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              d="M5 13l4 4L19 7"
            ></path>
          </svg>
        </div>

        {/* Title and Order ID */}
        <h2 className={styles.title}>Order Placed</h2>
        <p className={styles.subtitle}>ID: {values.orderId || "ORD-8829-X"}</p>
      </div>

      {/* Order Details */}
      <div className={styles.details}>
        {/* Order Type and Direction */}
        <div className={styles.row}>
          <span className={styles.label}>Type</span>
          <span className={styles.value}>
            {values.direction} {values.orderType}
          </span>
        </div>

        {/* Symbol */}
        <div className={styles.row}>
          <span className={styles.label}>Symbol</span>
          <span className={styles.valueBold}>{values.symbol}</span>
        </div>

        {/* Notional Amount (formatted as currency) */}
        <div className={styles.row}>
          <span className={styles.label}>Notional</span>
          <span className={`${styles.value} ${styles.valueBold}`}>
            {formatCurrency(Number(values.notional), values.symbol.split("/")[0])}
          </span>
        </div>

        {/* Order Status */}
        <div className={styles.statusRow}>
          <span className={styles.label}>Status</span>
          <span className={styles.status}>Pending Fill</span>
        </div>
      </div>

      {/* Action Buttons */}
      <div className={styles.actions}>
        {/* Amend: Make order editable again */}
        <button onClick={amend} className={styles.btnAmend}>
          Amend
        </button>

        {/* New Order: Clear form and start fresh */}
        <button onClick={handleNewOrder} className={styles.btnNew}>
          New Order
        </button>
      </div>
    </div>
  );
};
